# Generated by Django 5.2.5 on 2025-08-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
