# Generated by Django 5.2.5 on 2025-08-10 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymm', '0002_alter_contactus_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactUs',
            new_name='contact',
        ),
    ]
